security:
  encoders:
          FOS\UserBundle\Model\UserInterface: bcrypt
  role_hierarchy:
          ROLE_ADMIN:       ROLE_USER
          ROLE_GOD: ROLE_ADMIN

  providers:
          fos_userbundle:
              id: fos_user.user_provider.username


  firewalls:
          main:
              pattern: ^/
              form_login:
                  provider: fos_userbundle
                  csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
              logout:       true
              anonymous:    true
              remember_me:
                              key:      "%secret%"
                              lifetime: 31536000 # 365 days in seconds
                              path:     /
                              domain:   ~ # Defaults to the current domain from $_SERVER
#          auth:
#              pattern: ^/api/*
#              api_key: true
#              stateless: true
#              provider: db
  access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/user_data/, role: ROLE_USER}
          - { path: ^/user_data/, role: ROLE_USER}
          - { path: ^/api/v1/, role: ROLE_USER}
          - { path: ^/admin/, role: ROLE_ADMIN }
  providers:
        in_memory:
            memory: ~
  firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
