country:
    path:     /
    defaults: { _controller: "AcmeEventManagerBundle:Country:index" }

country_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeEventManagerBundle:Country:show" }

country_new:
    path:     /new
    defaults: { _controller: "AcmeEventManagerBundle:Country:new" }

country_create:
    path:     /create
    defaults: { _controller: "AcmeEventManagerBundle:Country:create" }
    methods:  POST

country_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeEventManagerBundle:Country:edit" }

country_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeEventManagerBundle:Country:update" }
    methods:  [POST, PUT]

country_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeEventManagerBundle:Country:delete" }
    methods:  [POST, DELETE]
