admin_event:
    path:     /
    defaults: { _controller: "AcmeEventManagerBundle:Event:index" }

admin_event_new:
    path:     /new
    defaults: { _controller: "AcmeEventManagerBundle:Event:new" }

admin_event_create:
    path:     /create
    defaults: { _controller: "AcmeEventManagerBundle:Event:create" }
    methods:  POST

admin_event_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeEventManagerBundle:Event:edit" }

admin_event_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeEventManagerBundle:Event:update" }
    methods:  [POST, PUT]

admin_event_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeEventManagerBundle:Event:delete" }
    methods:  [POST, DELETE]

admin_event_statistics:
    path:   /{id}/statistics
    defaults: { _controller: "AcmeEventManagerBundle:Event:eventStatistics" }
    methods: GET

admin_event_participants:
    path:   /{id}/participants/{type}/{period}/
    defaults: { _controller: "AcmeEventManagerBundle:Event:eventParticipants" }
    methods: GET

admin_export_event_participants_to_csv:
    path:   /{id}/participants/export-to-csv/{type}/{period}/
    defaults: { _controller: "AcmeEventManagerBundle:Event:exportParticipantsToCSV" }

admin_event_papers:
    path:   /{id}/papers/{type}/{period}
    defaults: { _controller: "AcmeEventManagerBundle:Event:eventPapers" }
