user_data_new:
    path:     /new/{dataRequired}
    defaults: { _controller: "AcmeEventManagerBundle:UserData:new", dataRequired: "false" }

user_data_create:
    path:     /create
    defaults: { _controller: "AcmeEventManagerBundle:UserData:create" }
    methods:  POST

user_data_edit:
    path:     /edit
    defaults: { _controller: "AcmeEventManagerBundle:UserData:edit" }

user_data_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeEventManagerBundle:UserData:update" }
    methods:  [POST, PUT]
