services:
    acme_event_manager.edition_handler:
        class: Acme\Bundle\EventManagerBundle\Model\EditionHandler
        arguments: [@security.token_storage]
    acme_event_manager.creation_handler:
        class: Acme\Bundle\EventManagerBundle\Model\CreationHandler
        arguments: [@security.token_storage]
    acme_event_manager.csv_parser:
        class: Acme\Bundle\EventManagerBundle\Util\CSVParser
    acme_event_manager.csv_import_handler:
        class: Acme\Bundle\EventManagerBundle\Util\CSVImportHandler
        arguments: [@doctrine.orm.default_entity_manager, @acme_event_manager.creation_handler]
    acme_event_manager.csv_export_handler:
        class: Acme\Bundle\EventManagerBundle\Util\CSVExportHandler
        arguments: [@doctrine.orm.default_entity_manager, @acme_event_manager.event_participants_provider]
    acme_event_manager.api_request_handler:
        class: Acme\Bundle\EventManagerBundle\Model\ApiRequestHandler
        arguments: [@doctrine.orm.default_entity_manager]
    acme_event_manager.event_participation_handler:
        class: Acme\Bundle\EventManagerBundle\Model\ParticipationInEventHandler
        arguments: [@doctrine.orm.default_entity_manager, @security.token_storage, @acme_event_manager.creation_handler]
    acme_event_manager.event_statistic_provider:
        class: Acme\Bundle\EventManagerBundle\Model\EventStatisticProvider
        arguments: [@doctrine.orm.default_entity_manager]
    acme_event_manager.event_participants_provider:
        class: Acme\Bundle\EventManagerBundle\Model\ParticipantsProvider
        arguments: [@doctrine.orm.default_entity_manager]
    acme_event_manager.paper_addition_handler:
        class: Acme\Bundle\EventManagerBundle\Model\PaperAdditionHandler
        arguments: [@doctrine.orm.default_entity_manager, @security.token_storage, @acme_event_manager.creation_handler, @acme_event_manager.event_participation_handler]
    acme_event_manager.event_papers_provider:
        class: Acme\Bundle\EventManagerBundle\Model\PapersProvider
        arguments: [@doctrine.orm.default_entity_manager]
    acme_event_manager.pdf_export_handler:
        class: Acme\Bundle\EventManagerBundle\Util\PdfExportHandler
        arguments:  [@spraed.pdf.generator]
#    acme_event_manager.example:
#        class: Acme\Bundle\EventManagerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
